# Generated by Django 2.0.2 on 2018-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='shortname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
