# Generated by Django 2.0.2 on 2018-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0004_permissions_master_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='securiymessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
