# Generated by Django 2.0.2 on 2018-04-18 21:03

from django.db import migrations, models
import maqluengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0006_auto_20180413_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='static/site-images/tara_logo.png', upload_to=maqluengine.models.content_file_name),
        ),
    ]
