# Generated by Django 2.0.2 on 2018-05-02 21:21

from django.db import migrations, models
import maqluengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0007_auto_20180418_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='background_image',
            field=models.ImageField(default='', upload_to=maqluengine.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formproject',
            name='banner_image',
            field=models.ImageField(default='', upload_to=maqluengine.models.get_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formproject',
            name='font_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AddField(
            model_name='formproject',
            name='ui_colorA',
            field=models.CharField(default='#0057b9', max_length=10),
        ),
        migrations.AddField(
            model_name='formproject',
            name='ui_colorB',
            field=models.CharField(default='#00a1ff', max_length=10),
        ),
        migrations.AddField(
            model_name='formproject',
            name='ui_colorC',
            field=models.CharField(default='#5959c7', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='project-images/tara/tara_logo.png', upload_to=maqluengine.models.content_file_name),
        ),
    ]
