# Generated by Django 2.0.2 on 2018-06-06 15:42

from django.db import migrations, models
import maqluengine.models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0008_auto_20180502_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='formproject',
            name='ui_colorD',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='background_image',
            field=models.ImageField(null=True, upload_to=maqluengine.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='formproject',
            name='banner_image',
            field=models.ImageField(null=True, upload_to=maqluengine.models.get_image_path),
        ),
    ]
