# Generated by Django 2.0.2 on 2018-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0010_formtype_primary_thumbnail_reference_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='is_geospatial',
            field=models.BooleanField(default=False),
        ),
    ]
