# Generated by Django 2.0.2 on 2018-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0011_formtype_is_geospatial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrecordattributevalue',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
