# Generated by Django 2.0.2 on 2018-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0012_formrecordattributevalue_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrecordreferencevalue',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
