# Generated by Django 2.0.2 on 2018-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqluengine', '0014_webpage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
